---
name: docs-release
on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: deploy docs (branch)
    runs-on: ubuntu-20.04

    steps:
    - name: get branch name
      # could just hardcode master, but in case i add more branches in the future
      run: echo ::set-env name=FOLDERNAME::${GITHUB_REF#refs/*/}

    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: "15"

    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.11.1

    - name: install dependencies
      run: pnpm i

    - name: build docs
      run: npm run docs

    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: false
